### ISSUE TITLE
Glide guess not searching on vendor folder

### ISSUE THREAD

**Issue by leonfs** [Masterminds/glide#122]
I've been trying to use the guess feature but always returns an error.

    Oops! cannot find package "github.com/GoogleCloudPlatform/kubernetes/pkg/api" in any of:
	/usr/local/Cellar/go/1.5.1/libexec/src/github.com/GoogleCloudPlatform/kubernetes/pkg/api (from $GOROOT)
	/Workspace/go/src/github.com/GoogleCloudPlatform/kubernetes/pkg/api (from $GOPATH)

Though I do have the package under the vendor folder (obtained through Glide). The env variable GO15VENDOREXPERIMENT is set to 1.

**Comment by mattfarina** [comment]
@leonfs what version of glide are you using? You can run `glide --version` to get the details.

**Comment by leonfs** [comment]
Hi @mattfarina. I'm running version 0.6.1. I've checked before creating the issue, in case I was running an old version, but as it seemed to be the latest so I though this was a bug.

**Comment by mattfarina** [comment]
@leonfs I believe we've fixed that on master already. A new release (0.7.0) should becoming next week that will include that fix. We have a couple features we want to land before we push that out.

**Comment by leonfs** [comment]
Yeap. Just did. 

go get {master}
make install

glide -v shows the new build. 

But "glide guess" still throws the error. =(

**Comment by leonfs** [comment]
@mattfarina my fault... Is working..
