### ISSUE TITLE
Update failed for appengine/cloudsql: Cannot detect VCS

### ISSUE THREAD

**Issue by itscaro** [Masterminds/glide#272]
I'm stuggling with go 1.6 and glide 0.9

I got this error when getting go-sql-driver/mysql

Any ideas?

**Comment by akutz** [comment]
HA! I'm literally trying to solve the *same* issue! https://travis-ci.org/emccode/rexray/builds/110459662

**Comment by bwiggs** [comment]
Same here:

```
[INFO] Fetching appengine/cloudsql into /home/ubuntu/.go_workspace/src/github.com/...../vendor
[WARN] Error looking for appengine/cloudsql: Cannot detect VCS
[INFO] Downloading dependencies. Please wait...
[INFO] Fetching updates for appengine/cloudsql.
[WARN] Unable to checkout appengine/cloudsql
[ERROR] Update failed for appengine/cloudsql: Cannot detect VCS
```

**Comment by akutz** [comment]
FWIW, not Go 1.6 issue as happened on 1.5.1 on Travis as well. I bumped to 1.6 to see if that helped. Same error. See previous builds in my linked build's history for same error with 1.5.1.

**Comment by akutz** [comment]
Here's a build with 1.5.1 with same error. https://travis-ci.org/emccode/rexray/builds/110452312

**Comment by mattfarina** [comment]
@itscaro @bwiggs are you pulling the tip of master or using the released version?

@akutz I see your case. It's pulling the tip of master. I think you're seeing a problem because of #267. If you build in appengine there are some special appengine packages available. The change in #267 allows glide to scan all possible dependencies, irregardless of build mode, so it can get the full picture. Unfortunately, that means it tried to find appengine based dependencies as well.

I'm debating between two possible fixes.

1. Skip appengine dependencies.
2. Provide a flag to only build for the current environment (GOOS/GOARCH)

**Comment by akutz** [comment]
Hi @mattfarina,

FWIW, here's the bit from the Makefile that handles Glide. In a branch I update REX-Ray to use Gomk for builds, which I've designed to enable selecting the version of Glide I want to use. Currently it's using the tip of master.

```
deps: _pre-make _deps _post-make
_deps:
    @if [ -z "$$OFFLINE" ]; then \
        echo "target: deps"; \
        printf "  ...installing glide..."; \
        go get github.com/Masterminds/glide; \
            $(PRINT_STATUS); \
        printf "  ...glide up..."; \
            cd $(BASEDIR); \
            $(GLIDE) up $(MAKE_LOG_FD); \
            $(PRINT_STATUS); \
        printf "  ...go get..."; \
            go get -d $(GOFLAGS) $(NV); \
            $(PRINT_STATUS); \
    fi
```

**Comment by akutz** [comment]
Hi @mattfarina,

Ah, thanks for the response. Yes, I had to [do something similar in Gomk](https://github.com/akutz/gomk/blob/master/.gomk/include/tools/source/govet.mk) for `go vet` as that tool did not function correctly when using an OS/ARCH separate from the host.

**Comment by akutz** [comment]
FWIW, I think option number two makes the most sense.

**Comment by mattfarina** [comment]
@akutz I'm thinking of handling both options. Appengine is an annoying special case and the flag would be useful.

**Comment by akutz** [comment]
Why is Appengine so annoying? Just curious. Because it's on Github but has import path from Google?

**Comment by mattfarina** [comment]
The appengine import is `appengine` and not a remote location. It's a special case build mode for appengine where the SDK (import of `appengine`) is available in the same way standard library packages are. It's a special case where two Google products (appengine and Go) are colluding in a non-standard way.

**Comment by akutz** [comment]
Ruxin from the League agrees :)

![image](https://cloud.githubusercontent.com/assets/101085/13187928/f0544a58-d713-11e5-9e59-87a688d2fa6b.png)

**Comment by mattfarina** [comment]
This should now be fixed. If not please re-open the issue.

**Comment by akutz** [comment]
Hi @mattfarina,

So it failed on Travis again. https://travis-ci.org/emccode/rexray/builds/110459662

However, it worked locally when I updated Glide. I am resending my commit to Travis instead of just rerunning the build in case Travis had cached the Glide sources. I don't tell it to, but I don't know another explanation.

**Comment by akutz** [comment]
Nope, still failing - https://travis-ci.org/emccode/rexray/builds/110483778. I just nuked my local vendor dir and am trying a full `glide up` again locally to see if the reason it worked locally earlier was from caching.

**Comment by akutz** [comment]
Hi @mattfarina,

It's failing locally. The reason it worked was because I had not actually upgraded Glide to 0.9 locally. I neglected the `-u` flag in `go get`. I just used it to upgrade to the tip of master, and it's failing locally as well. 

```
[0]akutz@pax:rexray$ glide up
[INFO] Downloading dependencies. Please wait...
[INFO] Fetching updates for github.com/spf13/viper.
[INFO] Fetching updates for github.com/goamz/goamz.
[INFO] Fetching updates for github.com/akutz/golf.
[INFO] Fetching updates for gopkg.in/yaml.v2.
[INFO] Fetching updates for github.com/akutz/goof.
[INFO] Fetching updates for github.com/spf13/cobra.
[INFO] Fetching updates for github.com/akutz/gotil.
[INFO] Fetching updates for golang.org/x/net.
[INFO] Fetching updates for github.com/emccode/goscaleio.
[INFO] Fetching updates for github.com/akutz/gofig.
[INFO] Fetching updates for github.com/emccode/govmax.
[INFO] Fetching updates for github.com/appropriate/go-virtualboxclient.
[INFO] Fetching updates for github.com/rackspace/gophercloud.
[INFO] Fetching updates for github.com/emccode/goisilon.
[INFO] Fetching updates for google.golang.org/api.
[INFO] Fetching updates for github.com/emccode/goxtremio.
[INFO] Fetching updates for gopkg.in/yaml.v1.
[INFO] Fetching updates for github.com/go-yaml/yaml.
[INFO] Fetching updates for github.com/spf13/pflag.
[INFO] Setting version for github.com/goamz/goamz to 5c85623a00092be41b679e53ef47772cf8ded1da.
[INFO] Setting version for github.com/rackspace/gophercloud to 42196eaf5b93739d335921404bb7c5f2205fceb3.
[INFO] Setting version for gopkg.in/yaml.v1 to b4a9f8c4b84c6c4256d669c649837f1441e4b050.
[INFO] Setting version for github.com/spf13/pflag to b084184666e02084b8ccb9b704bf0d79c466eb1d.
[INFO] Setting version for github.com/akutz/goof to master.
[INFO] Setting version for github.com/akutz/gofig to master.
[INFO] Setting version for github.com/emccode/goxtremio to 89e87d4bdf43837a161fd36ad8dd32e0ce42ae98.
[INFO] Setting version for github.com/emccode/goscaleio to 29678665e99b627013b8b9f2727bbdaed79bbd05.
[INFO] Setting version for github.com/emccode/goisilon to f9b53f0aaadb12a26b134830142fc537f492cb13.
[INFO] Setting version for golang.org/x/net to master.
[INFO] Setting version for gopkg.in/yaml.v2 to b4a9f8c4b84c6c4256d669c649837f1441e4b050.
[INFO] Setting version for github.com/go-yaml/yaml to b4a9f8c4b84c6c4256d669c649837f1441e4b050.
[INFO] Setting version for github.com/spf13/viper to support/rexray.
[INFO] Setting version for github.com/spf13/cobra to 363816bb13ce1710460c2345017fd35593cbf5ed.
[INFO] Setting version for github.com/akutz/gotil to master.
[INFO] Setting version for github.com/emccode/govmax to 39eb25ef96221a595aea883ffded341d37750d51.
[INFO] Setting version for github.com/akutz/golf to v0.1.1.
[INFO] Setting version for google.golang.org/api to fd081149e482b10c55262756934088ffe3197ea3.
[INFO] Setting version for github.com/appropriate/go-virtualboxclient to e0978ab2ed407095400a69d5933958dd260058cd.
[INFO] Resolving imports
[INFO] Fetching github.com/cpuguy83/go-md2man/md2man into /Users/akutz/Projects/go/src/github.com/emccode/rexray/vendor
[INFO] Fetching github.com/inconshreveable/mousetrap into /Users/akutz/Projects/go/src/github.com/emccode/rexray/vendor
[INFO] Fetching github.com/BurntSushi/toml into /Users/akutz/Projects/go/src/github.com/emccode/rexray/vendor
[INFO] Fetching github.com/kr/pretty into /Users/akutz/Projects/go/src/github.com/emccode/rexray/vendor
[INFO] Fetching github.com/magiconair/properties into /Users/akutz/Projects/go/src/github.com/emccode/rexray/vendor
[INFO] Fetching github.com/mitchellh/mapstructure into /Users/akutz/Projects/go/src/github.com/emccode/rexray/vendor
[INFO] Fetching github.com/spf13/cast into /Users/akutz/Projects/go/src/github.com/emccode/rexray/vendor
[INFO] Fetching github.com/spf13/jwalterweatherman into /Users/akutz/Projects/go/src/github.com/emccode/rexray/vendor
[INFO] Fetching gopkg.in/fsnotify.v1 into /Users/akutz/Projects/go/src/github.com/emccode/rexray/vendor
[INFO] Fetching github.com/Sirupsen/logrus into /Users/akutz/Projects/go/src/github.com/emccode/rexray/vendor
[INFO] Setting version for github.com/Sirupsen/logrus to feature/logrus-aware-types.
[INFO] Fetching github.com/kardianos/osext into /Users/akutz/Projects/go/src/github.com/emccode/rexray/vendor
[INFO] Setting version for github.com/kardianos/osext to master.
[INFO] Fetching github.com/docker/docker/pkg/mount into /Users/akutz/Projects/go/src/github.com/emccode/rexray/vendor
[INFO] Fetching github.com/gorilla/handlers into /Users/akutz/Projects/go/src/github.com/emccode/rexray/vendor
[INFO] Fetching github.com/gorilla/mux into /Users/akutz/Projects/go/src/github.com/emccode/rexray/vendor
[INFO] Fetching github.com/opencontainers/runc/libcontainer/label into /Users/akutz/Projects/go/src/github.com/emccode/rexray/vendor
[INFO] Fetching golang.org/x/oauth2/google into /Users/akutz/Projects/go/src/github.com/emccode/rexray/vendor
[INFO] Fetching github.com/vmware/govmomi into /Users/akutz/Projects/go/src/github.com/emccode/rexray/vendor
[INFO] Setting version for github.com/vmware/govmomi to 4739ba797cc0c7240e0848e724fb733e6b08bc9c.
[INFO] Fetching github.com/russross/blackfriday into /Users/akutz/Projects/go/src/github.com/emccode/rexray/vendor
[INFO] Fetching github.com/kr/text into /Users/akutz/Projects/go/src/github.com/emccode/rexray/vendor
[INFO] Fetching github.com/gorilla/context into /Users/akutz/Projects/go/src/github.com/emccode/rexray/vendor
[INFO] Fetching google.golang.org/appengine into /Users/akutz/Projects/go/src/github.com/emccode/rexray/vendor
[INFO] Fetching google.golang.org/cloud/compute/metadata into /Users/akutz/Projects/go/src/github.com/emccode/rexray/vendor
[INFO] Fetching github.com/shurcooL/sanitized_anchor_name into /Users/akutz/Projects/go/src/github.com/emccode/rexray/vendor
[INFO] Fetching github.com/golang/protobuf/proto into /Users/akutz/Projects/go/src/github.com/emccode/rexray/vendor
[INFO] Fetching appengine_internal into /Users/akutz/Projects/go/src/github.com/emccode/rexray/vendor
[WARN] Error looking for appengine_internal: Cannot detect VCS
[INFO] Fetching appengine_internal/base into /Users/akutz/Projects/go/src/github.com/emccode/rexray/vendor
[WARN] Error looking for appengine_internal/base: Cannot detect VCS
[INFO] Downloading dependencies. Please wait...
[INFO] Fetching updates for appengine_internal/base.
[INFO] Fetching updates for appengine_internal.
[WARN] Unable to checkout appengine_internal
[ERROR] Update failed for appengine_internal: Cannot detect VCS
[WARN] Unable to checkout appengine_internal/base
[ERROR] Update failed for appengine_internal/base: Cannot detect VCS
[ERROR] Could not update packages: Cannot detect VCS
Cannot detect VCS
[1]akutz@pax:rexray$ 
```

**Comment by akutz** [comment]
I'm an idiot. Didn't realize just added the flag. Thought you were also handling appengine as a special case. The flag works :)

**Comment by mattfarina** [comment]
I seem to have missed an app engine specific package.

**Comment by mattfarina** [comment]
@akutz this "should" now be fixed and I tested against rexray.
