### ISSUE TITLE
glide.sh domain name issues - expired?

### ISSUE THREAD

**Issue by bradleyfalzon** [Masterminds/glide#784]
Just having some issues installing glide:

```
curl https://glide.sh/get
curl: (6) Could not resolve host: glide.sh; Name or service not known
```

Checking .sh name servers show no NS records for glide.sh, so I don't think it's a local issue.

```
dig @ns-a1.sh. ns glide.sh

; <<>> DiG 9.9.4-RedHat-9.9.4-38.el7_3.2 <<>> @ns-a1.sh. ns glide.sh
; (2 servers found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NXDOMAIN, id: 57167
;; flags: qr aa rd; QUERY: 1, ANSWER: 0, AUTHORITY: 1, ADDITIONAL: 1
;; WARNING: recursion requested but not available

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;glide.sh.                      IN      NS

;; AUTHORITY SECTION:
sh.                     3600    IN      SOA     ns1.communitydns.net. admin.nic.sh. 1489884332 3600 1800 3600000 3600

;; Query time: 883 msec
;; SERVER: 194.0.1.1#53(194.0.1.1)
;; WHEN: Sun Mar 19 11:58:08 ACDT 2017
;; MSG SIZE  rcvd: 107
```

Checking https://www.nic.sh whois lists the domain currently as expired:

```
Domain Name :	glide.sh ... (Check glide.ac) ... (Check glide.io)
Domain Status :	Expired/Suspended
First Registered :	2016-02-16
Last Updated :	2017-03-19
Expiry :	2017-02-16 ... Redemption Grace Period Ends, 2017-05-18 00:30
```

Workarounds:

- Use the latest release from https://github.com/Masterminds/glide/releases and manually install
- Use master `go get -u github.com/Masterminds/glide`

**Comment by gpinkham** [comment]
I did this for a work-around
````
RUN wget https://github.com/Masterminds/glide/releases/download/v0.12.3/glide-v0.12.3-linux-386.tar.gz
RUN tar xzvf glide-v0.12.3-linux-386.tar.gz
RUN linux-386/glide install
````

**Comment by hayeah** [comment]
I build glide into my golang base image. The following command copies glide into go bin

```
RUN wget https://github.com/Masterminds/glide/releases/download/v0.12.3/glide-v0.12.3-linux-amd64.tar.gz && \
  tar xzvf glide-v0.12.3-linux-amd64.tar.gz && \
  cp linux-amd64/glide /go/bin/glide && \
  rm -r linux-amd64 && rm glide-v0.12.3-linux-amd64.tar.gz
```

**Comment by bradleyfalzon** [comment]
Note if you are in the golang base image or have go available, `go get -u github.com/Masterminds/glide` is probably good enough, but tracks master, not their tagged releases.

**Comment by franciscocpg** [comment]
Hi guys
You may want to run `curl https://raw.githubusercontent.com/Masterminds/glide.sh/master/get | sh`

https://github.com/Masterminds/glide.sh is the repo for `glide.sh`

**Comment by umair0538** [comment]
`curl https://raw.githubusercontent.com/Masterminds/glide.sh/master/get | sh` doesn't work as it uses glide.sh internally. `go get -u github.com/Masterminds/glide` just works fine!

**Comment by franciscocpg** [comment]
@umair0538, you're right
It's using `https://glide.sh/version` :disappointed: 
But as already said https://github.com/Masterminds/glide/issues/784#issuecomment-287705352, `go get -u github.com/Masterminds/glide` doesn't get the latest stable release.

**Comment by sysradium** [comment]
So will the glide.sh go away?

**Comment by franciscocpg** [comment]
I think the only person who knows this one is @mattfarina

**Comment by ryanleary** [comment]
No statement or diagnosis here yet? It's been over two days now!

**Comment by sysradium** [comment]
There is no activity on twitter as well. Maybe the guy is just on a vacation. Can't blame him :)

**Comment by kofalt** [comment]
For the time being, you can probably grab from
https://raw.githubusercontent.com/Masterminds/glide.sh/master/get

Instead of 
https://glide.sh/get

This is not legal advice, not tested on animals, some assembly required, etc.

**Comment by bradleyfalzon** [comment]
@kofalt note because that script itself uses glide.sh domain to fetch the version, it won't quite work.

**Comment by mattfarina** [comment]
This should be fixed soon. Fox already submitted. Sorry about the delay. Happened while I was on vacation. You'll see me back on glide more regularly soon

**Comment by pauloelr** [comment]
It is still not working, even after the pull request was merged.

```
$ curl https://raw.githubusercontent.com/Masterminds/glide.sh/master/get | sh
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  3241  100  3241    0     0   3288      0 --:--:-- --:--:-- --:--:--  3287
Fail to install glide
```

Exit Code: `6`

**Comment by bradleyfalzon** [comment]
I don't believe the issue is resolved until the domain has been added to the .sh name servers.

Checking the name servers for glide.sh still yields no results (for a positive match, change glide.sh to nic.sh).

```
for i in `dig ns sh +short`; do echo querying $i; dig @$i ns glide.sh +short; done

querying ns-d1.sh.
querying ns-y1.sh.

; <<>> DiG 9.8.3-P1 <<>> @ns-y1.sh. ns glide.sh +short
; (1 server found)
;; global options: +cmd
;; connection timed out; no servers could be reached
querying ns-a2.sh.
querying ns-l1.sh.
querying ns-a4.sh.
querying ns-a1.sh.
querying ns-a3.sh.
```

**Comment by JumpeiArashi** [comment]
```
$whois glide.sh

Domain : glide.sh
Status : pendingDelete
Expiry : 2017-02-16
Delete : 2017-05-18 00:30
```
A month passed.

**Comment by ryanleary** [comment]
I've registered getglide.sh. As soon as it goes through, I will have it hosted on S3/Cloudfront so folks can feel free to switch to that domain.

@Masterminds folks feel free to reach out and as soon as the real glide.sh domain is fixed, I'll transfer getglide.sh to you.

**Comment by ryanleary** [comment]
https://getglide.sh is now live and mirroring the glide.sh repo, modulo the `get` file modified to point to `https://getglide.sh/version` internally.

**Comment by mattfarina** [comment]
glide.sh is back

**Comment by GNSubrahmanyam** [comment]
<pre><font color="#EEE8D5">curl https://glide.sh/get | sh</font>
<font color="#EEE8D5">  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current</font>
<font color="#EEE8D5">                                 Dload  Upload   Total   Spent    Left  Speed</font>
<font color="#EEE8D5">  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (6) Could not resolve host: glide.sh</font>
</pre>
